spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/stackOverflowClone
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properites:
      hibernate:
        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#   org.hibernate.type:trace